### ISSUE TITLE
Справочник кодов неполный

### ISSUE THREAD

**Issue by Georgsius** [hflabs/party-state#1]
Сейчас дадата выдает коды, которых нет в этом справочнике, например мне встретились 301, 302, 304

**Comment by nalgeon** [comment]
Дайте примеры конкретных ИНН, пожалуйста.

**Comment by nalgeon** [comment]
Добавили в db6ca6b5c6cc38cf96ce1f9f74529d1131a8cecb. Если напишете примеры ИНН — проверим их.
